version: '3.9'

services:
  postgres_db:
    container_name: db
    image: postgres:16
    ports: # port exposed to the host machine
      - "5432:5432"
    volumes: # volume used to persist data
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres