spring:
  application:
    name : weemeal-backend-spring
#  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password: password
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: "org.hibernate.dialect.H2Dialect"