on:
  release:
    types:
      - published
env:
  IMAGE_NAME: weemeal-backend-spring

jobs:
  register:
    name: Package, Publish, and Register
    runs-on:
      - ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v3
      - if: ${{ github.event_name != 'pull_request' || ! github.event.pull_request.head.repo.fork }}
        uses: docker/login-action@v2.2.0
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}
      - name: install pack
        run: (curl -sSL "https://github.com/buildpacks/pack/releases/download/v0.35.1/pack-v0.35.1-linux.tgz" | sudo tar -C /usr/local/bin/ --no-same-owner -xzv pack)
      - name: Build image
        run: pack build docker.io/darthkali/${{ env.IMAGE_NAME }}:${{ github.event.release.tag_name }}
          --tag docker.io/darthkali/${{ env.IMAGE_NAME }}:latest
          --builder paketobuildpacks/builder:base
          --env "BP_JVM_VERSION=21"
          --publish